spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pcmarket
    username: postgres
    password: java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api



